name: Drjoy Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ollama_review:
    runs-on: self-hosted
    name: Drjoy Code Review
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v43
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.swift
            **.kt
            **.java

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.get-modified-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - uses: vudvv/CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_API_URL: http://127.0.0.1:11434
          LANGUAGE: English
          MODEL: llama3.2
          PROMPT: Please check if there are any confusions or irregularities in the following code diff
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
          IGNORE_PATTERNS: /node_modules/**/*,*.md # glob pattern or regex pattern to ignore files, separated by comma
          INCLUDE_PATTERNS: "*.js,*.swift,*.kt"
          TARGET_LABEL: "AI-REVIEW"
