name: Drjoy Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ollama_review:
    runs-on: self-hosted
    name: Drjoy Code Review
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.get-modified-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      - name: Read review criteria from file
        id: read_criteria
        run: echo "PROMPT_DRJOY=$(cat review_criteria.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - uses: vudvv/CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OLLAMA_API_URL: http://127.0.0.1:11434
          LANGUAGE: English
          MODEL: llama3.2
          PROMPT: ${{ env.PROMPT_DRJOY }}
          PROMPT_DRJOY: As a software engineer, please review the following code, provide suggestions for improvement, coding best practices, improve readability, maintainability, and as briefly as posible.
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
          IGNORE_PATTERNS: /node_modules/**/*,*.md # glob pattern or regex pattern to ignore files, separated by comma
          INCLUDE_PATTERNS: "*.js,*.swift,*.kt"
          TARGET_LABEL: "AI-REVIEW"
          TARGET_CRITERIA_LABEL: "AI-CRITERIA-REVIEW"
