name: Automated Ollama Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ollama_review:
    runs-on: self-hosted
    name: Ollama Code Review Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v43

      - name: Review modified files
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
        run: |
          # curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3.2", "prompt": "Review the following file:let a = 0", "stream": false}' | python3 -c "import sys, json; print(json.load(sys.stdin)['response'])"
          # modified_file_review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3.2", "prompt": "Review the following file:let a = 0", "stream": false}' | python3 -c "import sys, json; print(json.load(sys.stdin)['response'])")
          # file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"
          # echo "$file_comment" >> ollama_review.txt
          # Ensure the changed files list is available
          for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
            # Get the code changes (diff) for the file
            file_diff=$(git diff HEAD~1 -- "$file")

            # Check if there are changes (skip empty diffs)
            if [[ -z "$file_diff" ]]; then
              echo "No changes detected in $file."
              continue
            fi

            # Format the diff into a prompt for Ollama
            prompt="Review the following code changes in the file: $file\n\n\`\`\`\n$file_diff\n\`\`\`"

            # Call Ollama API to review the diff
            modified_file_review=$(curl -s http://127.0.0.1:11434/api/generate \
              -d "{\"model\": \"llama3.2\", \"prompt\": \"$prompt\", \"stream\": false}" \
              | python3 -c "import sys, json; print(json.load(sys.stdin)['response'])")

            # Format the review comment
            file_comment="Ollama Code Review for \`$file\`:\n\n$modified_file_review"

            # Append the review to a text file
            echo "$file_comment" >> ollama_review.txt

            echo "Review for $file written to ollama_review.txt"
            gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
          done


          
        shell: bash
