name: Automated Ollama Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ollama_review:
    runs-on: self-hosted
    name: Ollama Code Review Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get modified files
        id: get-modified-files
        uses: tj-actions/changed-files@v43
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.swift
            **.kt
            **.java

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.get-modified-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Review modified files
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
          echo $file
          content=$(git diff origin/main -- "$file" || echo "Failed to get diff for $file")
          content=${content//\'/\'\'}
          content=${content//\"/\\\"}
          content=$(echo "$content" | tr '\n' ' ')
          echo $content
          review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3.2", "prompt": "As a software engineer, please review the following code, provide suggestions for improvement, coding best practices, improve readability, and maintainability.:\n\n```\n'"${content}"'\n```", "stream": false}' | jq -r '.response')
          echo $review

          if [[ $review == "null" ]]
          then
            comments="Ollama Code Review for \`$file\`: All good!"
          else
            comments="Ollama Code Review for \`$file\`:\n\n$review"
            # Use echo -e to interpret \n as newlines
            comments=$(echo -e "$comments")
          fi
          done
        shell: bash
